/**
   * Canonical seed data for geography master tables.
   * Owned by seed-geography.ts.
   *
   * State and city rows reference parents by code (country_code, state_code)
   * rather than by integer id, so the seeder can resolve FKs at insert time
   * without depending on auto-increment id values.
   */

  export const COUNTRY_MASTER_SEED = [
    { country_code: "US", country_name: "United States" },
  { country_code: "CA", country_name: "Canada" },
  { country_code: "GB", country_name: "United Kingdom" },
  { country_code: "DE", country_name: "Germany" },
  { country_code: "FR", country_name: "France" },
  { country_code: "JP", country_name: "Japan" },
  { country_code: "AU", country_name: "Australia" },
  { country_code: "IN", country_name: "India" },
  { country_code: "BR", country_name: "Brazil" },
  { country_code: "MX", country_name: "Mexico" },
  { country_code: "IT", country_name: "Italy" },
  { country_code: "ES", country_name: "Spain" },
  { country_code: "NL", country_name: "Netherlands" },
  { country_code: "SE", country_name: "Sweden" },
  { country_code: "SG", country_name: "Singapore" },
  { country_code: "KR", country_name: "South Korea" },
  { country_code: "CN", country_name: "China" },
  ];

  export const STATE_MASTER_SEED = [
    { state_code: "NSW", state_name: "New South Wales", country_code: "AU" },
  { state_code: "QLD", state_name: "Queensland", country_code: "AU" },
  { state_code: "SA", state_name: "South Australia", country_code: "AU" },
  { state_code: "TAS", state_name: "Tasmania", country_code: "AU" },
  { state_code: "VIC", state_name: "Victoria", country_code: "AU" },
  { state_code: "WA", state_name: "Western Australia", country_code: "AU" },
  { state_code: "BA", state_name: "Bahia", country_code: "BR" },
  { state_code: "MG", state_name: "Minas Gerais", country_code: "BR" },
  { state_code: "RJ", state_name: "Rio de Janeiro", country_code: "BR" },
  { state_code: "RS", state_name: "Rio Grande do Sul", country_code: "BR" },
  { state_code: "SP", state_name: "São Paulo", country_code: "BR" },
  { state_code: "AB", state_name: "Alberta", country_code: "CA" },
  { state_code: "BC", state_name: "British Columbia", country_code: "CA" },
  { state_code: "MB", state_name: "Manitoba", country_code: "CA" },
  { state_code: "NB", state_name: "New Brunswick", country_code: "CA" },
  { state_code: "NL", state_name: "Newfoundland and Labrador", country_code: "CA" },
  { state_code: "NS", state_name: "Nova Scotia", country_code: "CA" },
  { state_code: "ON", state_name: "Ontario", country_code: "CA" },
  { state_code: "PE", state_name: "Prince Edward Island", country_code: "CA" },
  { state_code: "QC", state_name: "Quebec", country_code: "CA" },
  { state_code: "SK", state_name: "Saskatchewan", country_code: "CA" },
  { state_code: "BJ", state_name: "Beijing", country_code: "CN" },
  { state_code: "GD", state_name: "Guangdong", country_code: "CN" },
  { state_code: "JS", state_name: "Jiangsu", country_code: "CN" },
  { state_code: "SH", state_name: "Shanghai", country_code: "CN" },
  { state_code: "ZJ", state_name: "Zhejiang", country_code: "CN" },
  { state_code: "BE", state_name: "Berlin", country_code: "DE" },
  { state_code: "BW", state_name: "Baden-Württemberg", country_code: "DE" },
  { state_code: "BY", state_name: "Bavaria", country_code: "DE" },
  { state_code: "HE", state_name: "Hesse", country_code: "DE" },
  { state_code: "HH", state_name: "Hamburg", country_code: "DE" },
  { state_code: "NI", state_name: "Lower Saxony", country_code: "DE" },
  { state_code: "NW", state_name: "North Rhine-Westphalia", country_code: "DE" },
  { state_code: "SN", state_name: "Saxony", country_code: "DE" },
  { state_code: "AN", state_name: "Andalusia", country_code: "ES" },
  { state_code: "CT", state_name: "Catalonia", country_code: "ES" },
  { state_code: "MD", state_name: "Madrid", country_code: "ES" },
  { state_code: "ARA", state_name: "Auvergne-Rhône-Alpes", country_code: "FR" },
  { state_code: "IDF", state_name: "Île-de-France", country_code: "FR" },
  { state_code: "OCC", state_name: "Occitanie", country_code: "FR" },
  { state_code: "PAC", state_name: "Provence-Alpes-Côte d'Azur", country_code: "FR" },
  { state_code: "ENG", state_name: "England", country_code: "GB" },
  { state_code: "NIR", state_name: "Northern Ireland", country_code: "GB" },
  { state_code: "SCT", state_name: "Scotland", country_code: "GB" },
  { state_code: "WLS", state_name: "Wales", country_code: "GB" },
  { state_code: "DL", state_name: "Delhi", country_code: "IN" },
  { state_code: "GJ", state_name: "Gujarat", country_code: "IN" },
  { state_code: "KA", state_name: "Karnataka", country_code: "IN" },
  { state_code: "MH", state_name: "Maharashtra", country_code: "IN" },
  { state_code: "RJ", state_name: "Rajasthan", country_code: "IN" },
  { state_code: "TG", state_name: "Telangana", country_code: "IN" },
  { state_code: "TN", state_name: "Tamil Nadu", country_code: "IN" },
  { state_code: "UP", state_name: "Uttar Pradesh", country_code: "IN" },
  { state_code: "WB", state_name: "West Bengal", country_code: "IN" },
  { state_code: "LAZ", state_name: "Lazio", country_code: "IT" },
  { state_code: "LOM", state_name: "Lombardy", country_code: "IT" },
  { state_code: "PIE", state_name: "Piedmont", country_code: "IT" },
  { state_code: "VEN", state_name: "Veneto", country_code: "IT" },
  { state_code: "HK", state_name: "Hokkaido", country_code: "JP" },
  { state_code: "KY", state_name: "Kyoto", country_code: "JP" },
  { state_code: "OK", state_name: "Okinawa", country_code: "JP" },
  { state_code: "OS", state_name: "Osaka", country_code: "JP" },
  { state_code: "TK", state_name: "Tokyo", country_code: "JP" },
  { state_code: "BSN", state_name: "Busan", country_code: "KR" },
  { state_code: "ICN", state_name: "Incheon", country_code: "KR" },
  { state_code: "SEL", state_name: "Seoul", country_code: "KR" },
  { state_code: "CMX", state_name: "Ciudad de México", country_code: "MX" },
  { state_code: "JAL", state_name: "Jalisco", country_code: "MX" },
  { state_code: "NLE", state_name: "Nuevo León", country_code: "MX" },
  { state_code: "YUC", state_name: "Yucatán", country_code: "MX" },
  { state_code: "NB", state_name: "North Brabant", country_code: "NL" },
  { state_code: "NH", state_name: "North Holland", country_code: "NL" },
  { state_code: "ZH", state_name: "South Holland", country_code: "NL" },
  { state_code: "AB", state_name: "Stockholm", country_code: "SE" },
  { state_code: "M", state_name: "Skåne", country_code: "SE" },
  { state_code: "VG", state_name: "Västra Götaland", country_code: "SE" },
  { state_code: "SG", state_name: "Singapore", country_code: "SG" },
  { state_code: "AK", state_name: "Alaska", country_code: "US" },
  { state_code: "AL", state_name: "Alabama", country_code: "US" },
  { state_code: "AR", state_name: "Arkansas", country_code: "US" },
  { state_code: "AZ", state_name: "Arizona", country_code: "US" },
  { state_code: "CA", state_name: "California", country_code: "US" },
  { state_code: "CO", state_name: "Colorado", country_code: "US" },
  { state_code: "CT", state_name: "Connecticut", country_code: "US" },
  { state_code: "DC", state_name: "District of Columbia", country_code: "US" },
  { state_code: "DE", state_name: "Delaware", country_code: "US" },
  { state_code: "FL", state_name: "Florida", country_code: "US" },
  { state_code: "GA", state_name: "Georgia", country_code: "US" },
  { state_code: "HI", state_name: "Hawaii", country_code: "US" },
  { state_code: "IA", state_name: "Iowa", country_code: "US" },
  { state_code: "ID", state_name: "Idaho", country_code: "US" },
  { state_code: "IL", state_name: "Illinois", country_code: "US" },
  { state_code: "IN", state_name: "Indiana", country_code: "US" },
  { state_code: "KS", state_name: "Kansas", country_code: "US" },
  { state_code: "KY", state_name: "Kentucky", country_code: "US" },
  { state_code: "LA", state_name: "Louisiana", country_code: "US" },
  { state_code: "MA", state_name: "Massachusetts", country_code: "US" },
  { state_code: "MD", state_name: "Maryland", country_code: "US" },
  { state_code: "ME", state_name: "Maine", country_code: "US" },
  { state_code: "MI", state_name: "Michigan", country_code: "US" },
  { state_code: "MN", state_name: "Minnesota", country_code: "US" },
  { state_code: "MO", state_name: "Missouri", country_code: "US" },
  { state_code: "MS", state_name: "Mississippi", country_code: "US" },
  { state_code: "MT", state_name: "Montana", country_code: "US" },
  { state_code: "NC", state_name: "North Carolina", country_code: "US" },
  { state_code: "ND", state_name: "North Dakota", country_code: "US" },
  { state_code: "NE", state_name: "Nebraska", country_code: "US" },
  { state_code: "NH", state_name: "New Hampshire", country_code: "US" },
  { state_code: "NJ", state_name: "New Jersey", country_code: "US" },
  { state_code: "NM", state_name: "New Mexico", country_code: "US" },
  { state_code: "NV", state_name: "Nevada", country_code: "US" },
  { state_code: "NY", state_name: "New York", country_code: "US" },
  { state_code: "OH", state_name: "Ohio", country_code: "US" },
  { state_code: "OK", state_name: "Oklahoma", country_code: "US" },
  { state_code: "OR", state_name: "Oregon", country_code: "US" },
  { state_code: "PA", state_name: "Pennsylvania", country_code: "US" },
  { state_code: "RI", state_name: "Rhode Island", country_code: "US" },
  { state_code: "SC", state_name: "South Carolina", country_code: "US" },
  { state_code: "SD", state_name: "South Dakota", country_code: "US" },
  { state_code: "TN", state_name: "Tennessee", country_code: "US" },
  { state_code: "TX", state_name: "Texas", country_code: "US" },
  { state_code: "UT", state_name: "Utah", country_code: "US" },
  { state_code: "VA", state_name: "Virginia", country_code: "US" },
  { state_code: "VT", state_name: "Vermont", country_code: "US" },
  { state_code: "WA", state_name: "Washington", country_code: "US" },
  { state_code: "WI", state_name: "Wisconsin", country_code: "US" },
  { state_code: "WV", state_name: "West Virginia", country_code: "US" },
  { state_code: "WY", state_name: "Wyoming", country_code: "US" },
  ];

  export const CITY_MASTER_SEED = [
    { city_name: "Sydney", postal_code: "2000", state_code: "NSW", country_code: "AU" },
  { city_name: "Sydney", postal_code: "2010", state_code: "NSW", country_code: "AU" },
  { city_name: "Brisbane", postal_code: "4000", state_code: "QLD", country_code: "AU" },
  { city_name: "Adelaide", postal_code: "5000", state_code: "SA", country_code: "AU" },
  { city_name: "Hobart", postal_code: "7000", state_code: "TAS", country_code: "AU" },
  { city_name: "Melbourne", postal_code: "3000", state_code: "VIC", country_code: "AU" },
  { city_name: "Perth", postal_code: "6000", state_code: "WA", country_code: "AU" },
  { city_name: "Salvador", postal_code: "40020-000", state_code: "BA", country_code: "BR" },
  { city_name: "Belo Horizonte", postal_code: "30130-000", state_code: "MG", country_code: "BR" },
  { city_name: "Rio de Janeiro", postal_code: "20040-020", state_code: "RJ", country_code: "BR" },
  { city_name: "Porto Alegre", postal_code: "90010-000", state_code: "RS", country_code: "BR" },
  { city_name: "São Paulo", postal_code: "01000-000", state_code: "SP", country_code: "BR" },
  { city_name: "Calgary", postal_code: "T2P 1J9", state_code: "AB", country_code: "CA" },
  { city_name: "Edmonton", postal_code: "T5J 0R7", state_code: "AB", country_code: "CA" },
  { city_name: "Vancouver", postal_code: "V6B 1A1", state_code: "BC", country_code: "CA" },
  { city_name: "Vancouver", postal_code: "V6C 3N1", state_code: "BC", country_code: "CA" },
  { city_name: "Winnipeg", postal_code: "R3C 0V8", state_code: "MB", country_code: "CA" },
  { city_name: "Fredericton", postal_code: "E3B 1A1", state_code: "NB", country_code: "CA" },
  { city_name: "St. John's", postal_code: "A1C 5T7", state_code: "NL", country_code: "CA" },
  { city_name: "Halifax", postal_code: "B3J 1P3", state_code: "NS", country_code: "CA" },
  { city_name: "Ottawa", postal_code: "K1P 5G3", state_code: "ON", country_code: "CA" },
  { city_name: "Toronto", postal_code: "M5H 2N2", state_code: "ON", country_code: "CA" },
  { city_name: "Toronto", postal_code: "M5V 3L9", state_code: "ON", country_code: "CA" },
  { city_name: "Charlottetown", postal_code: "C1A 4J9", state_code: "PE", country_code: "CA" },
  { city_name: "Montreal", postal_code: "H2X 1Y4", state_code: "QC", country_code: "CA" },
  { city_name: "Montreal", postal_code: "H3B 1A3", state_code: "QC", country_code: "CA" },
  { city_name: "Regina", postal_code: "S4P 3C4", state_code: "SK", country_code: "CA" },
  { city_name: "Beijing", postal_code: "100000", state_code: "BJ", country_code: "CN" },
  { city_name: "Guangzhou", postal_code: "510000", state_code: "GD", country_code: "CN" },
  { city_name: "Nanjing", postal_code: "210000", state_code: "JS", country_code: "CN" },
  { city_name: "Shanghai", postal_code: "200000", state_code: "SH", country_code: "CN" },
  { city_name: "Hangzhou", postal_code: "310000", state_code: "ZJ", country_code: "CN" },
  { city_name: "Berlin", postal_code: "10115", state_code: "BE", country_code: "DE" },
  { city_name: "Berlin", postal_code: "10117", state_code: "BE", country_code: "DE" },
  { city_name: "Stuttgart", postal_code: "70173", state_code: "BW", country_code: "DE" },
  { city_name: "Munich", postal_code: "80331", state_code: "BY", country_code: "DE" },
  { city_name: "Frankfurt", postal_code: "60311", state_code: "HE", country_code: "DE" },
  { city_name: "Hamburg", postal_code: "20095", state_code: "HH", country_code: "DE" },
  { city_name: "Hanover", postal_code: "30159", state_code: "NI", country_code: "DE" },
  { city_name: "Düsseldorf", postal_code: "40213", state_code: "NW", country_code: "DE" },
  { city_name: "Dresden", postal_code: "01067", state_code: "SN", country_code: "DE" },
  { city_name: "Seville", postal_code: "41001", state_code: "AN", country_code: "ES" },
  { city_name: "Barcelona", postal_code: "08001", state_code: "CT", country_code: "ES" },
  { city_name: "Madrid", postal_code: "28001", state_code: "MD", country_code: "ES" },
  { city_name: "Lyon", postal_code: "69001", state_code: "ARA", country_code: "FR" },
  { city_name: "Paris", postal_code: "75001", state_code: "IDF", country_code: "FR" },
  { city_name: "Paris", postal_code: "75008", state_code: "IDF", country_code: "FR" },
  { city_name: "Toulouse", postal_code: "31000", state_code: "OCC", country_code: "FR" },
  { city_name: "Marseille", postal_code: "13001", state_code: "PAC", country_code: "FR" },
  { city_name: "Nice", postal_code: "06000", state_code: "PAC", country_code: "FR" },
  { city_name: "Birmingham", postal_code: "B1 1BB", state_code: "ENG", country_code: "GB" },
  { city_name: "London", postal_code: "EC1A 1BB", state_code: "ENG", country_code: "GB" },
  { city_name: "London", postal_code: "SW1A 1AA", state_code: "ENG", country_code: "GB" },
  { city_name: "Manchester", postal_code: "M1 1AD", state_code: "ENG", country_code: "GB" },
  { city_name: "Belfast", postal_code: "BT1 1AA", state_code: "NIR", country_code: "GB" },
  { city_name: "Edinburgh", postal_code: "EH1 1RE", state_code: "SCT", country_code: "GB" },
  { city_name: "Glasgow", postal_code: "G1 1AA", state_code: "SCT", country_code: "GB" },
  { city_name: "Cardiff", postal_code: "CF10 1EP", state_code: "WLS", country_code: "GB" },
  { city_name: "Delhi", postal_code: "110001", state_code: "DL", country_code: "IN" },
  { city_name: "Ahmedabad", postal_code: "380001", state_code: "GJ", country_code: "IN" },
  { city_name: "Bangalore", postal_code: "560001", state_code: "KA", country_code: "IN" },
  { city_name: "Mumbai", postal_code: "400001", state_code: "MH", country_code: "IN" },
  { city_name: "Jaipur", postal_code: "302001", state_code: "RJ", country_code: "IN" },
  { city_name: "Hyderabad", postal_code: "500001", state_code: "TG", country_code: "IN" },
  { city_name: "Chennai", postal_code: "600001", state_code: "TN", country_code: "IN" },
  { city_name: "Lucknow", postal_code: "226001", state_code: "UP", country_code: "IN" },
  { city_name: "Kolkata", postal_code: "700001", state_code: "WB", country_code: "IN" },
  { city_name: "Rome", postal_code: "00100", state_code: "LAZ", country_code: "IT" },
  { city_name: "Milan", postal_code: "20121", state_code: "LOM", country_code: "IT" },
  { city_name: "Turin", postal_code: "10121", state_code: "PIE", country_code: "IT" },
  { city_name: "Venice", postal_code: "30100", state_code: "VEN", country_code: "IT" },
  { city_name: "Sapporo", postal_code: "060-0001", state_code: "HK", country_code: "JP" },
  { city_name: "Kyoto", postal_code: "600-8008", state_code: "KY", country_code: "JP" },
  { city_name: "Osaka", postal_code: "530-0001", state_code: "OS", country_code: "JP" },
  { city_name: "Tokyo", postal_code: "100-0001", state_code: "TK", country_code: "JP" },
  { city_name: "Tokyo", postal_code: "160-0023", state_code: "TK", country_code: "JP" },
  { city_name: "Busan", postal_code: "48060", state_code: "BSN", country_code: "KR" },
  { city_name: "Incheon", postal_code: "22004", state_code: "ICN", country_code: "KR" },
  { city_name: "Seoul", postal_code: "04524", state_code: "SEL", country_code: "KR" },
  { city_name: "Mexico City", postal_code: "06000", state_code: "CMX", country_code: "MX" },
  { city_name: "Guadalajara", postal_code: "44100", state_code: "JAL", country_code: "MX" },
  { city_name: "Monterrey", postal_code: "64000", state_code: "NLE", country_code: "MX" },
  { city_name: "Mérida", postal_code: "97000", state_code: "YUC", country_code: "MX" },
  { city_name: "Eindhoven", postal_code: "5611", state_code: "NB", country_code: "NL" },
  { city_name: "Amsterdam", postal_code: "1012", state_code: "NH", country_code: "NL" },
  { city_name: "Rotterdam", postal_code: "3011", state_code: "ZH", country_code: "NL" },
  { city_name: "Stockholm", postal_code: "111 57", state_code: "AB", country_code: "SE" },
  { city_name: "Malmö", postal_code: "211 18", state_code: "M", country_code: "SE" },
  { city_name: "Gothenburg", postal_code: "411 05", state_code: "VG", country_code: "SE" },
  { city_name: "Singapore", postal_code: "018956", state_code: "SG", country_code: "SG" },
  { city_name: "Singapore", postal_code: "048583", state_code: "SG", country_code: "SG" },
  { city_name: "Anchorage", postal_code: "99501", state_code: "AK", country_code: "US" },
  { city_name: "Birmingham", postal_code: "35201", state_code: "AL", country_code: "US" },
  { city_name: "Little Rock", postal_code: "72201", state_code: "AR", country_code: "US" },
  { city_name: "Mesa", postal_code: "85201", state_code: "AZ", country_code: "US" },
  { city_name: "Phoenix", postal_code: "85001", state_code: "AZ", country_code: "US" },
  { city_name: "Phoenix", postal_code: "85003", state_code: "AZ", country_code: "US" },
  { city_name: "Tucson", postal_code: "85701", state_code: "AZ", country_code: "US" },
  { city_name: "Fresno", postal_code: "93650", state_code: "CA", country_code: "US" },
  { city_name: "Los Angeles", postal_code: "90001", state_code: "CA", country_code: "US" },
  { city_name: "Los Angeles", postal_code: "90012", state_code: "CA", country_code: "US" },
  { city_name: "Los Angeles", postal_code: "90015", state_code: "CA", country_code: "US" },
  { city_name: "Sacramento", postal_code: "95814", state_code: "CA", country_code: "US" },
  { city_name: "San Diego", postal_code: "92101", state_code: "CA", country_code: "US" },
  { city_name: "San Diego", postal_code: "92102", state_code: "CA", country_code: "US" },
  { city_name: "San Francisco", postal_code: "94102", state_code: "CA", country_code: "US" },
  { city_name: "San Francisco", postal_code: "94103", state_code: "CA", country_code: "US" },
  { city_name: "San Francisco", postal_code: "94104", state_code: "CA", country_code: "US" },
  { city_name: "San Jose", postal_code: "95110", state_code: "CA", country_code: "US" },
  { city_name: "San Jose", postal_code: "95112", state_code: "CA", country_code: "US" },
  { city_name: "Denver", postal_code: "80201", state_code: "CO", country_code: "US" },
  { city_name: "Denver", postal_code: "80202", state_code: "CO", country_code: "US" },
  { city_name: "Hartford", postal_code: "06101", state_code: "CT", country_code: "US" },
  { city_name: "Washington", postal_code: "20001", state_code: "DC", country_code: "US" },
  { city_name: "Washington", postal_code: "20002", state_code: "DC", country_code: "US" },
  { city_name: "Wilmington", postal_code: "19801", state_code: "DE", country_code: "US" },
  { city_name: "Jacksonville", postal_code: "32099", state_code: "FL", country_code: "US" },
  { city_name: "Miami", postal_code: "33101", state_code: "FL", country_code: "US" },
  { city_name: "Miami", postal_code: "33125", state_code: "FL", country_code: "US" },
  { city_name: "Orlando", postal_code: "32801", state_code: "FL", country_code: "US" },
  { city_name: "Tampa", postal_code: "33601", state_code: "FL", country_code: "US" },
  { city_name: "Atlanta", postal_code: "30301", state_code: "GA", country_code: "US" },
  { city_name: "Atlanta", postal_code: "30302", state_code: "GA", country_code: "US" },
  { city_name: "Honolulu", postal_code: "96801", state_code: "HI", country_code: "US" },
  { city_name: "Des Moines", postal_code: "50301", state_code: "IA", country_code: "US" },
  { city_name: "Boise", postal_code: "83701", state_code: "ID", country_code: "US" },
  { city_name: "Chicago", postal_code: "60601", state_code: "IL", country_code: "US" },
  { city_name: "Chicago", postal_code: "60602", state_code: "IL", country_code: "US" },
  { city_name: "Chicago", postal_code: "60603", state_code: "IL", country_code: "US" },
  { city_name: "Indianapolis", postal_code: "46201", state_code: "IN", country_code: "US" },
  { city_name: "Louisville", postal_code: "40201", state_code: "KY", country_code: "US" },
  { city_name: "New Orleans", postal_code: "70112", state_code: "LA", country_code: "US" },
  { city_name: "Boston", postal_code: "02101", state_code: "MA", country_code: "US" },
  { city_name: "Boston", postal_code: "02102", state_code: "MA", country_code: "US" },
  { city_name: "Baltimore", postal_code: "21201", state_code: "MD", country_code: "US" },
  { city_name: "Portland", postal_code: "04101", state_code: "ME", country_code: "US" },
  { city_name: "Detroit", postal_code: "48201", state_code: "MI", country_code: "US" },
  { city_name: "Minneapolis", postal_code: "55401", state_code: "MN", country_code: "US" },
  { city_name: "Kansas City", postal_code: "64101", state_code: "MO", country_code: "US" },
  { city_name: "St. Louis", postal_code: "63101", state_code: "MO", country_code: "US" },
  { city_name: "Jackson", postal_code: "39201", state_code: "MS", country_code: "US" },
  { city_name: "Billings", postal_code: "59101", state_code: "MT", country_code: "US" },
  { city_name: "Charlotte", postal_code: "28201", state_code: "NC", country_code: "US" },
  { city_name: "Raleigh", postal_code: "27601", state_code: "NC", country_code: "US" },
  { city_name: "Fargo", postal_code: "58102", state_code: "ND", country_code: "US" },
  { city_name: "Omaha", postal_code: "68101", state_code: "NE", country_code: "US" },
  { city_name: "Manchester", postal_code: "03101", state_code: "NH", country_code: "US" },
  { city_name: "Albuquerque", postal_code: "87101", state_code: "NM", country_code: "US" },
  { city_name: "Las Vegas", postal_code: "89101", state_code: "NV", country_code: "US" },
  { city_name: "Buffalo", postal_code: "14201", state_code: "NY", country_code: "US" },
  { city_name: "New York", postal_code: "10001", state_code: "NY", country_code: "US" },
  { city_name: "New York", postal_code: "10002", state_code: "NY", country_code: "US" },
  { city_name: "New York", postal_code: "10003", state_code: "NY", country_code: "US" },
  { city_name: "Rochester", postal_code: "14601", state_code: "NY", country_code: "US" },
  { city_name: "Cincinnati", postal_code: "45201", state_code: "OH", country_code: "US" },
  { city_name: "Cleveland", postal_code: "44101", state_code: "OH", country_code: "US" },
  { city_name: "Columbus", postal_code: "43085", state_code: "OH", country_code: "US" },
  { city_name: "Oklahoma City", postal_code: "73101", state_code: "OK", country_code: "US" },
  { city_name: "Portland", postal_code: "97201", state_code: "OR", country_code: "US" },
  { city_name: "Philadelphia", postal_code: "19101", state_code: "PA", country_code: "US" },
  { city_name: "Philadelphia", postal_code: "19102", state_code: "PA", country_code: "US" },
  { city_name: "Pittsburgh", postal_code: "15201", state_code: "PA", country_code: "US" },
  { city_name: "Providence", postal_code: "02901", state_code: "RI", country_code: "US" },
  { city_name: "Sioux Falls", postal_code: "57101", state_code: "SD", country_code: "US" },
  { city_name: "Memphis", postal_code: "38101", state_code: "TN", country_code: "US" },
  { city_name: "Nashville", postal_code: "37201", state_code: "TN", country_code: "US" },
  { city_name: "Austin", postal_code: "73301", state_code: "TX", country_code: "US" },
  { city_name: "Austin", postal_code: "78701", state_code: "TX", country_code: "US" },
  { city_name: "Dallas", postal_code: "75201", state_code: "TX", country_code: "US" },
  { city_name: "Dallas", postal_code: "75202", state_code: "TX", country_code: "US" },
  { city_name: "El Paso", postal_code: "79901", state_code: "TX", country_code: "US" },
  { city_name: "Fort Worth", postal_code: "76101", state_code: "TX", country_code: "US" },
  { city_name: "Houston", postal_code: "77001", state_code: "TX", country_code: "US" },
  { city_name: "Houston", postal_code: "77002", state_code: "TX", country_code: "US" },
  { city_name: "San Antonio", postal_code: "78201", state_code: "TX", country_code: "US" },
  { city_name: "San Antonio", postal_code: "78205", state_code: "TX", country_code: "US" },
  { city_name: "Salt Lake City", postal_code: "84101", state_code: "UT", country_code: "US" },
  { city_name: "Richmond", postal_code: "23218", state_code: "VA", country_code: "US" },
  { city_name: "Burlington", postal_code: "05401", state_code: "VT", country_code: "US" },
  { city_name: "Seattle", postal_code: "98101", state_code: "WA", country_code: "US" },
  { city_name: "Seattle", postal_code: "98102", state_code: "WA", country_code: "US" },
  { city_name: "Milwaukee", postal_code: "53201", state_code: "WI", country_code: "US" },
  { city_name: "Charleston", postal_code: "25301", state_code: "WV", country_code: "US" },
  { city_name: "Cheyenne", postal_code: "82001", state_code: "WY", country_code: "US" },
  ];
  